### ISSUE TITLE
Blueprints + flask-nav (documentation issue)

### ISSUE THREAD

**Issue by SkyLeach** [mbr/flask-nav#3]
I like your work here, but I have an issue with Blueprints-style implementations using flask-nav that may just be me not understanding the mechanism (I looked at the source,.. just...)

Ok, so Assuming a have a base navigation navbar (like topnav in the example) and I want to work with it I can't seem to find a way to avoid circular imports with flask-nav.  The callback Navbar constructor can place relative imports into quotes (ex: '.root') but unless every single blueprint module implements this function I'll get a render() error since the module currently importing base doesn't have have a .root method.

werkzeug.routing.BuildError: ('blueprintmodule.root', {}, None)

Attempting to use paths to avoid this also doesn't seem to work:

werkzeug.routing.BuildError: ('/', {}, None)

Is there something I'm missing or am I going to have to implement flask route deconstruction in the callback?

**Comment by mbr** [comment]
I am not entirely sure what you are trying to build, do you want to derive a navigation for each Blueprint ("work with it")?

If I understand you correctly, your issue is that you want to use relative endpoint names in your `Navbar`/`View`, but reuse said code for multiple blueprints that may not all implement the same endpoints?

If so, you could, for example, create one Navbar per Blueprint, factor out common items into another function and call it during construction. My own uses cases have been a lot simpler, I usually end up creating two navbars (one for the frontend, one for the admin/backend side) and just give these different names.

If you could provide more details or a concrete example, I may be able to help you out further.

**Comment by SkyLeach** [comment]
I don't want modules to have to worry about the nav bar most of the time.  In the cases, however, where they have module-specific items they can modify the previously registered navigaiton object.

So for instance I have a very few views registered on a module and they use the base template which includes flask-nav.  The only problem is, the templates are visible fine off of my views.py but break in the blueprints modules because I can't specify .views or myapp.views with flask-nav.  Both are incorrect in the context of of the template.

```
blueprinttest = Blueprint('blueprinttest', __name__)


@blueprinttest.route('/')
def api_forms():
    try:
        qgs = blueprintapi.connect(username='xxxx', password='xxxx')
        ret = qgs.request('asset_search.php', {
            'target_ips': '10.16.0.4',
        })
    except RequestException as reqe:
        ret = reqe.strerror

    # no-template just straight xml (commented out to move to a REST endpoint)
    # print(ret)
    # return Response(str(ret), mimetype='text/xml')
    # return ret, 200, {'Content-Type': 'text/css; charset=utf-8'}

    # simple template to wrap output
    return render_template('apiresults.html', xml=ret)


@blueprinttest.route('/dafuq')
def just_root():
    return render_template('index.html', cves=[])
# simple blueprint api wrapper to test it in flask (webserver)
```

Using a template like this:

```
{% extends 'base.html' %}
{% block content %}
<xmp>{{ xml }}</xmp>
{% endblock %}
```

with base.html containing the render call:

```
{% block styles %}
    {{super()}}
    {% assets "css_all" %}
        <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}"></script>
    {% endassets %}
{% endblock %}
{% block navbar %}
    {{nav.cvmsui_top.render()}}
{% endblock %}
{% block content %}
    {{super()}}
{% endblock %}

```

**Comment by SkyLeach** [comment]
It seems that one has to dispense with relative views to use flask-nav with blueprints.  This basically means that if you are using Blueprints, you can forget the 'easy' ways of adding a simple views.py or having endpoint decorators in the `__init__.py` because there is no way to construct a portable view object from them from outside of them.  the modulename isn't accessible to the view path and relative imports will work with the blueprints module.  I got around this by creating a root_context blueprint and converting my views.py into rootviews.py and then creating a new blueprint called root_context which exposed the default pages.

Not sure if you know of another way around this issue, but I sure couldn't find one without subclassing the view and disabling decorators entirely.

**Comment by mbr** [comment]
Could you add the code for your navigation in the example?

In your `base.html`, you are calling `nav.cvmsui_top.render()`, are you trying to override while keeping the same base template, so that each blueprint will render a specific navigation even though they're all based on the same `base.html`?

Also, I'm not sure what you mean by not being able to call `.views` - it should work the same as it does with `url_for`, returning the `views`-endpoint of the current blueprint.

**Comment by SkyLeach** [comment]
I'll try to explain this as I understand it, but I'm very new to flask (I'm coming from TG2) so please take my  offering for why I think this is happening with a little salt as I am by no means a flask expert.

The application is initialized as a module from which the routing is built and attached to an application context instantiated and defined by whichever module (either the module directory through `__init__.py` or the called module file `myapp.py`.  When using blueprints, one is extending the module context by registering each module with the application as endpoint handlers.  The decorators provide hooks for the application context to map callback functions to the routing context of the application.  Thus if I have endpoints exposed as follows:

```
__init__.py - exposes root() as '/' and login() as '/auth'
```

the flask maps them as `__name__.root` and not as `modulename.root`

Thus when I try to do the following:

```
def mynavbar(*args, **kwargs):
    return Navbar(
        View('Home', '.root'),
        View('Login', '.login'),
        # View('Forms Example', '.example_form'),
        # View('Debug-Info', 'debug.debug_root'),
        Subgroup(
            'Docs',
            Link('Flask-Bootstrap', 'http://pythonhosted.org/Flask-Bootstrap'),
            Link('Flask-AppConfig', 'https://github.com/mbr/flask-appconfig'),
            Link('Flask-Debug', 'https://github.com/mbr/flask-debug'),
            Separator(),
            Text('Bootstrap'),
            Link('Getting started', 'http://getbootstrap.com/getting-started/'),
            Link('CSS', 'http://getbootstrap.com/css/'),
            Link('Components', 'http://getbootstrap.com/components/'),
            Link('Javascript', 'http://getbootstrap.com/javascript/'),
            Link('Customize', 'http://getbootstrap.com/customize/'),
        ),
        Text('Using Flask-Bootstrap {}'.format(FLASK_BOOTSTRAP_VERSION)),
    )
```

Flask attempts to map them in the _relative module context_ when the view is rendered.  This means it would be `__name__` which doesn't really map to the context only to the module.  Since the module is incorrect and we need the context, we have to depend on something other than relative paths and module names aren't exactly safe either because of circular imports and the fact that the main context (in the case of using a simple `views.py` imported into the app by `__init__.py` via a standard `from myapp import views` the context path is not going to match the module path and thus `__name__`.path will yield the wrong result when the context is a blueprint module.

**Comment by mbr** [comment]
I believe there's a little misconception on your part; Flask applications, blueprints or other things are not modules at all.

There are two common ways of instantiating a Flask application, either by defining an app object directly or calling a factory function. While I prefer the latter form usually, I'll stick to the simpler for the sake of example. Take the hello-world-example straight from the Flask homepage:

``` python
from flask import Flask
app = Flask(__name__)

@app.route("/")
def hello():
    return "Hello World!"

if __name__ == "__main__":
    app.run()
```

Except for the import of the `Flask` constructor, no modules are involved here. The `@app.route`-decorator will spit out the function unchanged, but it will register an endpoint named "hello" in the `url_map`. The endpoint name is by default derived from the function's `__name__`, but can easily be overriden.

We can verify this interactively:

``` python
>>> from flask import Flask
>>> app = Flask('myapp')
>>> print(app)
<Flask 'myapp'>
>>> @app.route('/test')
... def test():
...     return 'this is the test route'
... 
>>> print app.url_map
Map([<Rule '/test' (HEAD, OPTIONS, GET) -> test>,
 <Rule '/static/<filename>' (HEAD, OPTIONS, GET) -> static>])
>>> @app.route('/other', endpoint='bar')
... def an_endpoint_with_a_different_name_than_the_function():
...     return 'this is bar'
... 
>>> print app.url_map
Map([<Rule '/other' (HEAD, OPTIONS, GET) -> bar>,
 <Rule '/test' (HEAD, OPTIONS, GET) -> test>,
 <Rule '/static/<filename>' (HEAD, OPTIONS, GET) -> static>])
```

There are no modules involved here (see http://stackoverflow.com/questions/19261833/what-is-an-endpoint-in-flask for more in-depth information), we can also check the endpoint works with `url_for`:

``` python
>>> from flask import url_for
>>> app.config['SERVER_NAME'] = 'localhost'  # required only in this example
>>> with app.app_context():
...     print url_for('bar')
... 
http://localhost/other
```

Note that I specifically did not have to write `an_endpoint_with_a_different_name_than_the_function` at any point.

## Blueprints

I believe Blueprints also work slightly different than you are currently assuming; it's easiest to think of them as a way to "pre-record" a registrations on the app that take place as soon as you call `register_blueprint`. Let's create a blueprint:

``` python
>>> from flask import Blueprint
>>> help(Blueprint)

>>> bp = Blueprint('mybp', 'bp')
>>> @bp.route('/hello')
... def hello():
...     return 'this is the blueprints hello func'
... 
>>> app.register_blueprint(bp, url_prefix='/bp')
>>> app.url_map
Map([<Rule '/bp/hello' (HEAD, OPTIONS, GET) -> mybp.hello>,
 <Rule '/other' (HEAD, OPTIONS, GET) -> bar>,
 <Rule '/test' (HEAD, OPTIONS, GET) -> test>,
 <Rule '/static/<filename>' (HEAD, OPTIONS, GET) -> static>])
```

(you can find a similar example in the official docs at http://flask.pocoo.org/docs/0.10/blueprints/)

The view functions of the blueprint are registered on the app, but prefixed with `blueprint_name.`. There's nothing magical about that and nothing is looked up at runtime - if you added extra routes to the blueprint now, they would not be picked up by app.

There is one caveat though: When inside a view that is part of a blueprint, the current blueprint is available using `request.blueprint`. Flask uses this to allow _relative_ endpoints: Any endpoint named that starts with a `.` will be transformed into `blueprint_name.`. Example:
- `hello` always finds the apps endpoints "hello"
- `foo.hello` finds the endpoint named "hello" from blueprint "foo"
- `bar.hello` finds the endpoint named "hello" from blueprint "bar"
- `.hello` finds the endpoint "hello" from "foo" if called from a view of "foo", likewise the "hello" from the app or "bar" otherwise.

At this point, I have to admit that the example in the Flask-Nav or Flask-Bootstrap docs may be a little confusing, usually you would want to give the absolute endpoint every time you use `View`:

``` python
# ...
return Navbar(
        View('Home', 'frontend.root'),
        View('Login', 'frontend.login'),
# ...
```

The above assumes that you have a blueprint named "frontend" that has these two view functions. Let's assume you use the app itself as the frontend (with a view named "index"), and have a blueprint for the admin interface:

``` python
# ...
return Navbar(
        View('Home', 'index'),
        View('Administration', 'admin.index'),
# ...
```

In closing, I'm still unsure what your application looks like, but normally, if you have a single navigational bar, you'll simply want to use absolute names for views.

**Comment by SkyLeach** [comment]
I've been a bit busy for the past few days, but I'll put up more information to show the issue I was having in more detail
